### ISSUE TITLE
Übersetzungen Im Vis-Editor auf Systemwerte zurückgesetzt

### ISSUE THREAD

**Issue by eric2905** [klein0r/ioBroker.trashschedule#25]
Mit der v0.0.7 werden die entspr. Übersetzungen im Vis-Editor deaktiviert und alle Überschriften werden mit den Systemnamen angezeigt (sieht Screenshot).

![D56C6E3F-0FF2-4F3E-A946-F49E78262077](https://user-images.githubusercontent.com/18639287/82006646-92b01580-9668-11ea-99b0-b2f9049fc875.jpeg)

Gleiches wurde auch bei Facebook beschrieben:
https://www.facebook.com/groups/440499112958264/permalink/1176030696071765/

Downgrade auf die v0.0.6 brachte sofort den Original-Zustand.

**Comment by Knallochse** [comment]
Leider kann ich dieses Verhalten im VIS-Editor nach Update auf V 0.0.7 bestätigen.

**Comment by GermanBluefox** [comment]
It is because of https://github.com/klein0r/ioBroker.trashschedule/blobmaster/widgets/trashschedule/words.js#L4

It must be: 
```
$.extend(true, systemDictionary, {
    "Text":            {...
});
```

**Comment by skvarel** [comment]
Hier leider das gleiche Verhalten. Bei der Version 0.6.0 ist noch alles in Ordnung.

**Comment by klein0r** [comment]
@GermanBluefox Thanks, I've already used extend (from create adapter template)

https://github.com/klein0r/ioBroker.trashschedule/blob/8bb10eed25ae6fb60140c19da75af8b42a17e6ce/widgets/trashschedule/js/trashschedule.js#L11-L15

The issue was the override of the systemDictionary in the words.js (copied from admin). I thought that file won't be parsed as JavaScript and is just a normal text in that context 😢 Maybe json would be the better solution here...

https://github.com/klein0r/ioBroker.trashschedule/blob/8bb10eed25ae6fb60140c19da75af8b42a17e6ce/widgets/trashschedule/words.js#L4-L17
